networks:
  web:
volumes:
  db:
  wp:

services:
  db:
    image: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - web
  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - '8080:80'
    volumes:
      - wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - web
